import express from "express";
import upload from "../middlewere/multer.js";
import {
  createGetFestival,
  createFestivalPage,
  updatedFestival,
  deleteFestivalImage,
  deleteCard,
} from "../controllers/festivalController.js";
import validateFileSize from "../middlewere/validateFileSize.js";

const festivalRoute = express.Router();

festivalRoute.get("/getfestival", createGetFestival);
festivalRoute.post(
  "/festivalRoute",
  upload.fields([
    {
      name: "heroImage",
      maxCount: 1,
    },
    { name: "cardImage0", maxCount: 1 },
    { name: "cardImage1", maxCount: 1 },
    { name: "cardImage2", maxCount: 1 },
    { name: "cardImage3", maxCount: 1 },
    { name: "cardImage4", maxCount: 1 },
    { name: "cardImage5", maxCount: 1 },
    { name: "cardImage6", maxCount: 1 },
    { name: "cardImage7", maxCount: 1 },
    { name: "cardImage8", maxCount: 1 },
    { name: "cardImage9", maxCount: 1 },
    {
      name: "advanceImage",
      maxCount: 1,
    },
    {
      name: "toplistImage",
      maxCount: 1,
    },
    {
      name: "robotImage",
      maxCount: 1,
    },
    {
      name: "competateImage",
      maxCount: 1,
    },
    {
      name: "runwayImage",
      maxCount: 1,
    },
    { name: "galleryImage0", maxCount: 1 },
    { name: "galleryImage1", maxCount: 1 },
    { name: "galleryImage2", maxCount: 1 },
    { name: "galleryImage3", maxCount: 1 },
    { name: "galleryImage4", maxCount: 1 },
    { name: "galleryImage5", maxCount: 1 },
    { name: "galleryImage6", maxCount: 1 },
    { name: "galleryImage7", maxCount: 1 },
    { name: "galleryImage8", maxCount: 1 },
    { name: "galleryImage9", maxCount: 1 },
    { name: "galleryImage10", maxCount: 1 },
    { name: "galleryImage11", maxCount: 1 },
    { name: "galleryImage12", maxCount: 1 },
    { name: "galleryImage13", maxCount: 1 },
    { name: "galleryImage14", maxCount: 1 },
    { name: "galleryImage15", maxCount: 1 },
    { name: "galleryImage16", maxCount: 1 },
    { name: "galleryImage17", maxCount: 1 },
    { name: "galleryImage18", maxCount: 1 },
    { name: "galleryImage19", maxCount: 1 },
    { name: "jurorImage0", maxCount: 1 },
    { name: "jurorImage1", maxCount: 1 },
    { name: "jurorImage2", maxCount: 1 },
    { name: "jurorImage3", maxCount: 1 },
    { name: "jurorImage4", maxCount: 1 },
    { name: "jurorImage5", maxCount: 1 },
    { name: "jurorImage6", maxCount: 1 },
    { name: "jurorImage7", maxCount: 1 },
    { name: "jurorImage8", maxCount: 1 },
    { name: "jurorImage9", maxCount: 1 },
    { name: "jurorImage10", maxCount: 1 },
    { name: "jurorImage11", maxCount: 1 },
    { name: "jurorImage12", maxCount: 1 },
    { name: "jurorImage13", maxCount: 1 },
    { name: "jurorImage14", maxCount: 1 },
    { name: "jurorImage15", maxCount: 1 },
    { name: "jurorImage16", maxCount: 1 },
    { name: "jurorImage17", maxCount: 1 },
    { name: "jurorImage18", maxCount: 1 },
    { name: "jurorImage19", maxCount: 1 },
  ]),
  validateFileSize,
  createFestivalPage,
);

festivalRoute.put(
  "/updatefestival/:id",
  upload.fields([
    { name: "heroImage", maxCount: 1 },
    { name: "advanceImage", maxCount: 1 },
    { name: "cardImage0", maxCount: 1 },
    { name: "cardImage1", maxCount: 1 },
    { name: "cardImage2", maxCount: 1 },
    { name: "cardImage3", maxCount: 1 },
    { name: "cardImage4", maxCount: 1 },
    { name: "cardImage5", maxCount: 1 },
    { name: "cardImage6", maxCount: 1 },
    { name: "cardImage7", maxCount: 1 },
    { name: "cardImage8", maxCount: 1 },
    { name: "cardImage9", maxCount: 1 },
    { name: "toplistImage", maxCount: 1 },
    { name: "robotImage", maxCount: 1 },
    { name: "competateImage", maxCount: 1 },
    { name: "runwayImage", maxCount: 1 },
    { name: "galleryImage0", maxCount: 1 },
    { name: "galleryImage1", maxCount: 1 },
    { name: "galleryImage2", maxCount: 1 },
    { name: "galleryImage3", maxCount: 1 },
    { name: "galleryImage4", maxCount: 1 },
    { name: "galleryImage5", maxCount: 1 },
    { name: "galleryImage6", maxCount: 1 },
    { name: "galleryImage7", maxCount: 1 },
    { name: "galleryImage8", maxCount: 1 },
    { name: "galleryImage9", maxCount: 1 },
    { name: "galleryImage10", maxCount: 1 },
    { name: "galleryImage11", maxCount: 1 },
    { name: "galleryImage12", maxCount: 1 },
    { name: "galleryImage13", maxCount: 1 },
    { name: "galleryImage14", maxCount: 1 },
    { name: "galleryImage15", maxCount: 1 },
    { name: "galleryImage16", maxCount: 1 },
    { name: "galleryImage17", maxCount: 1 },
    { name: "galleryImage18", maxCount: 1 },
    { name: "galleryImage19", maxCount: 1 },
    { name: "jurorImage0", maxCount: 1 },
    { name: "jurorImage1", maxCount: 1 },
    { name: "jurorImage2", maxCount: 1 },
    { name: "jurorImage3", maxCount: 1 },
    { name: "jurorImage4", maxCount: 1 },
    { name: "jurorImage5", maxCount: 1 },
    { name: "jurorImage6", maxCount: 1 },
    { name: "jurorImage7", maxCount: 1 },
    { name: "jurorImage8", maxCount: 1 },
    { name: "jurorImage9", maxCount: 1 },
    { name: "jurorImage10", maxCount: 1 },
    { name: "jurorImage11", maxCount: 1 },
    { name: "jurorImage12", maxCount: 1 },
    { name: "jurorImage13", maxCount: 1 },
    { name: "jurorImage14", maxCount: 1 },
    { name: "jurorImage15", maxCount: 1 },
    { name: "jurorImage16", maxCount: 1 },
    { name: "jurorImage17", maxCount: 1 },
    { name: "jurorImage18", maxCount: 1 },
    { name: "jurorImage19", maxCount: 1 },
  ]),
  validateFileSize,
  updatedFestival,
);

festivalRoute.delete("/deleteimage/:id", deleteFestivalImage);
festivalRoute.delete("/deletecard/:id", deleteCard);
export default festivalRoute;
